# pytest ищет этот конфиг-файл от рабочего каталога и выше — тот каталог, в котором pytest найдёт данный файл, станет rootdir (корневым каталогом) для pytest

[tool.pytest.ini_options]
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
