@startuml

!theme monokai from ..\.styles


abstract list
hide list empty members

abstract Organization {
    +title: <i>str</i>
    +head: Administrator
    +contacts: Contact
    +hire() → Personnel
    +fire() → Personnel
}

class University {
    +institutes: <i>list</i>[Institute]
}
class Institute {
    +departments: <i>list</i>[Department]
    +labs: <i>list</i>[Laboratory]
}
class Department {
    +groups: <i>list</i>[Group]
}
class Laboratory {
    +equipment: <i>list</i>[<i>str</i>]
    +schedule: <i>list</i>[<i>dict</i>[<i>datetime</i>, <i>timedelta</i>]]
}

class Group {
    +semester: <i>int</i>
    +curator: Teacher
    +head: Student
    +promote()
}


list <|-- Organization

Organization <|-- University
Organization <|-- Institute
Organization <|-- Department
Organization <|-- Laboratory

University o-- Institute
Institute o-- Department
Institute o-- Laboratory
Department o-- Group

list <|-- Group


'class Contact {
'    +mobile: <i>str</i>
'    +office: <i>str</i> | <i>None</i>
'    +email: <i>str</i> | <i>None</i>
'}
'hide Contact empty methods
'
'enum Sex {
'    MALE
'    FEMALE
'}
'hide Sex empty methods
'
'enum Degree {
'    CANDIDATE
'    DOCTOR
'}
'hide Degree empty methods
'
'abstract Person {
'    +last_name: <i>str</i>
'    +first_name: <i>str</i>
'    +patr_name: <i>str</i>
'    +sex: Sex
'    +birthdate: <i>date</i>
'    +contacts: Contact
'}
'abstract Personnel {
'    +id: <i>int</i>
'    +salary: <i>dec</i>
'    +position: <i>str</i>
'    +degree: Degree | <i>None</i>
'    +titles: <i>list</i>[<i>str</i>]
'    -exp: <i>dec</i>
'    ..<i> getters </i>..
'    +exp
''    ..<i> methods </i>..
'}
'class Teacher {
'    +courses: <i>list</i>[<i>str</i>]
'}
'class Administrator {
'
'}
'class Student {
'    +student_id: <i>str</i>
'    +grant: <i>dec</i>
'    +grade: <i>float</i>
'}
'
'
'Person <|-- Student
'Person <|-- Personnel
'Personnel <|-- Teacher
'Personnel <|-- Administrator
'
'Person *- Sex
'Person o-- Contact
'
'Personnel *- Degree

@enduml