@startuml
'https://plantuml.com/class-diagram

!theme monokai from ..\.styles

class Person {
    +name: <i>str</i>
    +sex: Gender
    __init__()
    __str__()
}

class Gender {
    +value: <i>str</i>
    __init__()
}

Person *-right- Gender

@enduml