# Generated by Django 4.2.7 on 2023-12-03 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(db_column='department_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='department', max_length=100)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='sponsor', max_length=250)),
            ],
            options={
                'db_table': 'sponsors',
            },
        ),
        migrations.CreateModel(
            name='Wards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='ward', max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
            ],
            options={
                'db_table': 'wards',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date', models.DateField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.sponsor')),
            ],
            options={
                'db_table': 'donations',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='sponsors',
            field=models.ManyToManyField(through='organization.Donation', to='organization.sponsor'),
        ),
    ]
